title: Your Site Name
description: A brief description of your site
baseurl: "" # You can leave this empty or set it to your repository name for GitHub Pages
url: "jczy3.github.io" # Your GitHub Pages URL

markdown: kramdown
theme: jekyll-theme-cayman # Or any other theme you are using

# Enable Sass / SCSS if needed
sass:
  style: compressed
  
sass:
  load_paths:
    - _sass # If you have a `_sass` folder for your SCSS partials
